quarkus:
  http:
    root-path: /
    non-application-root-path: /
  health:
    openapi:
      included: true
  smallrye-health:
    root-path: health
  swagger-ui:
    enable: true
    theme: original
    urls:
      health-v1: openapi-health-v1.json
      order-v1: openapi-order-v1-generated.json
