quarkus:
  http:
    host: 0.0.0.0
  log:
    level: INFO

  # DATABASE
  datasource:
    username: dev_user
    password: dev_password
    jdbc:
      url: jdbc:postgresql://localhost:5432/dev_db

  # AWS
  sns:
    endpoint-override: http://localhost:4566
    aws:
      region: eu-central-1
      credentials:
        type: static
        static-provider:
          access-key-id: test-key
          secret-access-key: test-secret
  sqs:
    endpoint-override: http://localhost:4566
    aws:
      region: eu-central-1
      credentials:
        type: static
        static-provider:
          access-key-id: test-key
          secret-access-key: test-secret


custom:
  # AWS
  sns:
    billing:
      topic-arn: arn:aws:sns:eu-central-1:000000000000:billing-dev-topic
      role-arn:
    shipping:
      topic-arn: arn:aws:sns:eu-central-1:000000000000:shipping-dev-topic
      role-arn:
  sqs:
    billing:
      queue-url: http://localhost:4566/000000000000/billing-dev-queue
      role-arn:
    shipping:
      queue-url: http://localhost:4566/000000000000/shipping-dev-queue
      role-arn:
