greeting:
  message: "Hello Scala RESTEasy"


### DEV ###
"%dev":
  quarkus:
    log:
      level: DEBUG

### INT ###
"%int":
  quarkus:
    log:
      level: INFO

### PROD ###
"%prod":
  quarkus:
    log:
      level: WARN
